### ISSUE TITLE
SetCursor() throws exception on Windows even when terminal appears to support the visibility

### ISSUE THREAD

**Issue by mitchellb613** [MV10/dotnet-curses#13]
```
Mindmagma.Curses.DotnetCursesException: SetCursor() returned ERR
   at Mindmagma.Curses.NativeExceptionHelper.ThrowOnFailure(Int32 result, String method)
   at Mindmagma.Curses.NCurses.SetCursor(Int32 cursorState)
   at roguelike_console.Game..ctor() in C:\Users\...\roguelike_console\Game.cs:line 22
```
Above is the error I get when I am running the following code:
`NCurses.SetCursor(CursesCursorState.VERY_VISIBLE);`

The strange thing is if I simply catch and log the exception, the cursor visibility does change as expected. I can set the cursors state to any of the options in `CursesCursorState` and it works visually but it always throws an error. This is on Windows 10 targeting net 6.0 with curses installed from the link in the readme of this repo.

**Comment by mitchellb613** [comment]
Disregard I was able to reproduce this in plain ncurses which proves it's not a bug in this library but rather something with ncurses and the windows terminal. This was the code that confirmed it for me because the behavior is exactly the same as I saw in dotnet-curses:

```
#include <ncurses.h>

int main()
{
    initscr();
    if (curs_set(0) == ERR)
    {
        printw("ERROR");
    }
    refresh();
    getch();
    endwin();
    return 0;
}
```

**Comment by MV10** [comment]
Interesting find, though. Thanks for reporting it and the followup.

Just out of curiosity, was that the built-in terminal (cmd.exe) or the new uber-fancy terminal?

I've been meaning to try this with the new one but haven't gotten around to installing it yet.

**Comment by leftbones** [comment]
> Interesting find, though. Thanks for reporting it and the followup.
> 
> Just out of curiosity, was that the built-in terminal (cmd.exe) or the new uber-fancy terminal?
> 
> I've been meaning to try this with the new one but haven't gotten around to installing it yet.

I just found this issue by searching about the same problem, decided to test this and found that it's throwing an error on both Windows Terminal AND Command Prompt.
