### ISSUE TITLE
embed libncursesw6.dll and other libraries in the assembly

### ISSUE THREAD

**Issue by yangzhongke** [MV10/dotnet-curses#6]
Thanks for your contribution.
I deem that there are few developers developing Text UI, I found your project out of interest. Because I used to develop a GUI-Framework with PyCurses: [https://github.com/yangzhongke/NAHA](https://github.com/yangzhongke/NAHA)

I have a question:why not embed libncursesw6.dll and other libraries in the assembly as embeded resources, and extract them to the working directory in the runtime, if so, developers do not need to distribute those files manually.

Thanks again for your contribution.

**Comment by MV10** [comment]
@yangzhongke Thanks for the suggestion (sorry for the delay, apparently github wasn't sending me notifications for a period of time). Your idea is interesting, but I don't intend to distribute third-party binaries. Anyone interested in a package like this already has the skills to locate and install those dependencies themselves.
