### ISSUE TITLE
trace function is not a part of standard ncurses api, remove it

### ISSUE THREAD

**Issue by rkhapov** [MV10/dotnet-curses#7]
Hello, i tried to use your library and got an exception when running a simple example:
```csharp
public void Run()
{
   try
   {
      var stdscr = NCurses.InitScreen();
   }
   finally
   {
     NCurses.EndWin();
   }
}
```
Exception was:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'Mindmagma.Curses.Interop.Native' threw an exception.
 ---> System.InvalidOperationException: No function was found with the name trace.
   at NativeLibraryLoader.NativeLibrary.LoadFunction[T](String name)
   at Mindmagma.Curses.Interop.Native.NativeToDelegate[D](String exportedFunctionName)
   at Mindmagma.Curses.Interop.Native..cctor()
   --- End of inner exception stack trace ---
   at Mindmagma.Curses.Interop.Native.initscr()
   at Mindmagma.Curses.NCurses.InitScreen()
   at Run() in /bla-bla-bla/:<line with InitScreen calling>
```

My os is fedora 31, uname -a:
```
Linux <bla-bla-bla> 5.5.7-200.fc31.x86_64
```

ncurses library was installed by _dnf install ncurses-devel_
ls /usr/lib64 | grep ncurses:
```
libncurses++.so
libncurses.so
libncurses++.so.5
libncurses.so.5
libncurses++.so.5.9
libncurses.so.5.9
libncurses++.so.6
libncurses.so.6
libncurses++.so.6.1
libncurses.so.6.1
libncurses++w.so
libncursesw.so
libncurses++w.so.5
libncursesw.so.5
libncurses++w.so.5.9
libncursesw.so.5.9
libncurses++w.so.6
libncursesw.so.6
libncurses++w.so.6.1
libncursesw.so.6.1
```

**Comment by rkhapov** [comment]
it is interesting to note, that _objdump -T libncurses* | grep "trace"_ in /usr/lib64
did not return anything

**Comment by rkhapov** [comment]
it means, that fedora libncurses did not contains trace function for some reasons

**Comment by rkhapov** [comment]
trace function is not a standard ncurses function

**Comment by rondunn** [comment]
Same problem on OSX:

{System.InvalidOperationException: No function was found with the name trace.
   at NativeLibraryLoader.NativeLibrary.LoadFunction[T](String name)
   at Mindmagma.Curses.Interop.Native.NativeToDelegate[D](String exportedFunctionName)
   at Mindmagma.Curses.Interop.Native..cctor()}

Blocking issue, no code will run.

**Comment by MaxiPaille** [comment]
Hello,
I have the same issue on OSX

**Comment by grzegorzkyc** [comment]
+1, same issue on macOS Catalina 10.15.6

`Unhandled exception. System.TypeInitializationException: The type initializer for 'Mindmagma.Curses.Interop.Native' threw an exception.
 ---> System.InvalidOperationException: No function was found with the name trace.
   at NativeLibraryLoader.NativeLibrary.LoadFunction[T](String name)
   at Mindmagma.Curses.Interop.Native.NativeToDelegate[D](String exportedFunctionName)
   at Mindmagma.Curses.Interop.Native..cctor()`

**Comment by MV10** [comment]
I'll accept a PR to remove that, but I don't have MacOS installed or running anywhere and Apple makes it nearly impossible to obtain without buying a Mac, which isn't going to ever happen. (Had an older version running in VM, but that is long gone.)

**Comment by dokpm0** [comment]
I was getting the same error on Gentoo Linux.  Gentoo's ncurses ebuild has an optional trace use flag that enables test trace() support in ncurses calls.  I rebuilt ncurses with that use flag enabled and no longer get the error.  But, as others have said, it's not standard.  The standard ncurses on most Linux distributions will not have a trace function.

**Comment by MV10** [comment]
I have merged a fix (thanks @joelday), I will try to find some time to crank out a new package soon.

**Comment by MV10** [comment]
Uploaded package v1.0.2, you should see it sometime later today after nuget finishes digesting it. Thanks everyone.

**Comment by grzegorzkyc** [comment]
Works fine on macOS Catalina 10.15.6, thank you
