### ISSUE TITLE
libncursesw6 not found on Win10

### ISSUE THREAD

**Issue by samuelventura** [MV10/dotnet-curses#9]
[HelloWorld.zip](https://github.com/MV10/dotnet-curses/files/4562612/HelloWorld.zip)

Environment:
- Windows 10 64x
- Dotnet SDK 3.1.201
- VS Studio Code
- OutputType=Exe
- TargetFramework=net462

```
$ dotnet --version
3.1.201
$ dotnet new console
$ dotnet add package dotnet-curses
$ dotnet run

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Mindmagma.Curses.Interop.Native' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Mindmagma.Curses.Interop.NCursesLibraryHandle' threw an exception. ---> System.IO.FileNotFoundException: Could not find or 
load the native library from any name: [ libncursesw6 ]
   at NativeLibraryLoader.LibraryLoader.LoadNativeLibrary(String[] names, PathResolver pathResolver)
   at Mindmagma.Curses.Interop.NCursesLibraryHandle.FindLibrary()
   at Mindmagma.Curses.Interop.NCursesLibraryHandle..cctor()
   --- End of inner exception stack trace ---
   at Mindmagma.Curses.Interop.Native.NativeToDelegate[D](String exportedFunctionName)
   at Mindmagma.Curses.Interop.Native..cctor()
   --- End of inner exception stack trace ---
   at Mindmagma.Curses.Interop.Native.initscr()
   at Mindmagma.Curses.NCurses.InitScreen()
   at HelloWorld.Program.Main(String[] args)
```

**Comment by MV10** [comment]
@samuelventura Hi, sorry for the delay, apparently github stopped notifying me of new posts.

The curses library is not included with Windows, you have to install it yourself. Is it in your path?

From the readme:

> For Windows, download it from Thomas Dickey’s site (the current ncurses maintainer) from the 64-bit link under the "MinGW Ports" heading on [this page](https://invisible-island.net/ncurses/#download_mingw), and extract the DLLs anywhere in your `%PATH%`.

**Comment by benj2240** [comment]
@samuelventura You may also see this error due to a 32-bit / 64-bit conflict.

I was able to resolve this error (on Windows 10, in a new .Net Framework console app) by unchecking "Prefer 32-bit" in the .csproj Build options.

**Comment by MV10** [comment]
Closing old issue, please open a new one if anyone has problems again.
